# Account
ACCOUNT: 1698945
PASSWORD: "42B12447b,"

# Stocks
CURRENCY_PEER: "EURUSD"
TIME_FRAME: 300
NUMBER: 5
START_DATE: "30.10.2020 21:35"
END_DATE: "30.10.2020 21:55"

# Settings
TIME_FORMAT: "%d.%m.%Y %H:%M"
